### ISSUE TITLE
came_from does not work because cookies are not set

### ISSUE THREAD

**Issue by mauritsvanrees** [collective/pas.plugins.oidc#11]
In case you don't mind much that came_from does not work, note that I think that the same is true for the other parameters that are set in the session: state, nonce, optionally verifier. The plugin works, so maybe these are all just optional for extra security, and are ignored when they are not there. A guess.

Anyway, with the standard Plone login form, a came_from parameter works. Visit this and after login you end up on the news page:

http://localhost:8080/Plone/login?came_from=http://localhost:8080/Plone/news

Using the oidc login form, this does not work, you end up on the homepage instead:

http://localhost:8080/Plone/acl_users/oidc/login?came_from=http://localhost:8080/Plone/news

The plugin does try to pass the came_from, everything seems to be correct. It saves it in the session, either via cookies or a "proper" session. After login has worked, it reads it from the session and redirects there.

Note that if you set `use_session_data_manager` to True in the plugin, because you use sessions in for example memcache, then Plone still needs to set a cookie once with the key to the session data.

I first thought the problem was that on the response we add a `Set-Cookie` header and then we redirect to the OIDC server. The cookie is for the Plone domain, not the OIDC domain (assuming this is different), so the browser ignores it. It could be that this is part of the problem, but the problem is deeper.

Apparently, when you add a `Set-Cookie` header on a redirect request, no cookie will be set by the browser. That is what I see on my Mac on Safari and Chrome.

Or maybe Zope/Plone removes this header when it does a redirect? No, with `curl` I *do* see a Set-Cookie header.

Stackoverflow describes the [same problem](https://stackoverflow.com/questions/57026956/on-safari-cookies-are-not-saved-when-sent-with-redirect#57119113). This question is about Safari/webkit, and the answer points to a [webkit issue](https://bugs.webkit.org/show_bug.cgi?id=3512). But it seems that more browsers share this behavior.  And the webkit issue suggests it is an HTTP protocol problem, if I interpret it correctly.

Another answer on the same stackoverflow question suggests to not use a redirect, but return a status 200 with an html page that does a [javascript redirect](https://stackoverflow.com/a/70295152/621201). A bit ugly, but that may do the trick.

Do other users of this plugin see the same?

**Comment by mauritsvanrees** [comment]
Seems a problem specific to the setup of the customer.

**Comment by mauritsvanrees** [comment]
@fredvd suspects Varnish is the problem, and he is right. It removes most cookies. See the `cookie-pass` and `cookie-whitelist` options in https://pypi.org/project/plone.recipe.varnish/

I think both options could be used. I chose to add `__ac_session` to the `cookie-pass` option.  The setting is then:

```
[varnish-configuration]
recipe = plone.recipe.varnish:configuration
...
cookie-pass = "auth_token|__ac(|_(name|password|persistent|session))=":"\.(js|css|kss)$"
```

Now it works!

What did not help during investigation, was that both Safari and Chrome do not show the `__ac_session` cookie in the sources/storage unless you are on the `/acl_users/oidc` path, which is the path that the cookie is set on. Firefox *does* show it, but initially I could not reach the test site due to an unrelated certificate problem...

It would be good to mention the cookie-pass option in the readme. I will make a PR.

**Comment by mamico** [comment]
@mauritsvanrees can I delete the branch `maurits-prevent-setcookie-problem-on-redirect`? it was related to this? thx

**Comment by mauritsvanrees** [comment]
Yes, this was used in PR #14, but it is closed and the code is not needed.  I have removed the branch.
