### ISSUE TITLE
Erro na documentação, url do campo Redirect uris 

### ISSUE THREAD

**Issue by fabriciocotag** [collective/pas.plugins.oidc#40]
Na documentação indica a configuração do Redirect uris como <Path to your Plone site>/login_oidc/oidc
Na verdade o correto é <Path to your Plone site>/login-oidc/oidc

**Comment by macagua** [comment]
@fabriciocotag If I understand this issue was resolved, right?

**Comment by macagua** [comment]
@fabriciocotag This issue was [resolved](https://github.com/collective/pas.plugins.oidc/blob/5245575d6e45cd47a16fdb24fb06d930d7b4e674/README.md?plain=1#L87) and merged into the ``main`` branch
