### ISSUE TITLE
Event required to indicate the creation of a new user

### ISSUE THREAD

**Issue by Arkusm** [collective/pas.plugins.oidc#53]
During the login process, an attempt is made to [create a new user](https://github.com/collective/pas.plugins.oidc/blob/e07e5fc773c51bc9090a058c82e50b11c5448b9a/src/pas/plugins/oidc/plugins.py#L183-L218) (plone member). I think that [IUserAdderPlugin](https://github.com/zopefoundation/Products.PluggableAuthService/blob/516d110f9852dbcb55ed492ada84f2b3d6a54e5c/src/Products/PluggableAuthService/interfaces/plugins.py#L148) is used for this. Unfortunately no plone event is triggered in this context or I don't know which one. Even if the creation of the user was successful. Normally such an event is always triggered when a new user is created, like [here](https://github.com/zopefoundation/Products.PluggableAuthService/blob/516d110f9852dbcb55ed492ada84f2b3d6a54e5c/src/Products/PluggableAuthService/events.py#L56).

My system uses a UsersAsContent implementation and I need such an event to create a new user object.

Can someone tell me if a corresponding event is triggered?

**Comment by erral** [comment]
I tried to do so (https://github.com/collective/pas.plugins.oidc/pull/41) trying to log in the user in portal_membership tool, but I failed because the request is not yet authenticated.

**Comment by Arkusm** [comment]
You could trigger an event in [plugins.py](https://github.com/collective/pas.plugins.oidc/blob/e07e5fc773c51bc9090a058c82e50b11c5448b9a/src/pas/plugins/oidc/plugins.py#L218).

```
from Products.PluggableAuthService.events import PrincipalCreated
from zope.event import notify
...
notify(PrincipalCreated(user))  # line 218 befor break
```

This works. You can then create a subscriber this way

```
  <!-- New Member created -->
  <subscriber
      for="Products.PluggableAuthService.interfaces.authservice.IPropertiedUser
           Products.PluggableAuthService.interfaces.events.IPrincipalCreatedEvent"
      handler=".updater.new_user"
      />
```

 But I don't know whether this is desired or should be done.

**Comment by erral** [comment]
I think it is desired. It should be so, because there is a specific event for that.
